drop table if exists booking;
drop table if exists comments;
drop table if exists items;
drop table if exists requests;
drop table if exists users;

create table if not exists users(
    id    bigint generated by default as identity not null,
    constraint user_pk primary key (id),
    name  varchar(200) not null,
    email varchar(500) not null,
    constraint uq_user_email unique (email)
);

--alter table users owner to shareit;
alter table users add owner bigint;

create table if not exists requests(
    id bigint generated by default as identity not null,
    constraint requests_pk primary key (id),
    description  varchar(200) not null,
    requester_id bigint       not null
    constraint requests_users_id_fk references users,
    created_date timestamp without time zone
);

--alter table requests owner to shareit;
alter table requests add owner bigint;

create table if not exists items (
    id bigint generated by default as identity not null,
    constraint items_pk primary key (id),
    name        varchar(50)  not null,
    description varchar(200) not null,
    available   boolean,
    owner_id    bigint
    constraint items_users_id_fk references users,
    request_id  bigint
    constraint items_requests_id_fk references requests
);

--alter table items owner to shareit;
alter table items add owner bigint;

create table if not exists booking(
    id bigint generated by default as identity not null,
    constraint booking_pk primary key (id),
    start_date timestamp without time zone not null,
    end_date   timestamp without time zone not null,
    item_id    bigint
    constraint booking_items_id_fk references items,
    booker_id  bigint
    constraint booking_users_id_fk references users,
    status     varchar(20)
);

--alter table booking owner to shareit;
alter table booking add owner bigint;

create table if not exists comments(
    id bigint generated by default as identity not null,
    constraint comments_pk primary key (id),
    text         varchar(500),
    item_id      bigint
    constraint comments_items_id_fk references items,
    user_id      bigint
    constraint comments_users_id_fk references users,
    created_date timestamp without time zone
);

--alter table comments owner to shareit;
alter table comments add owner bigint;